replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 3000

readinessProbe:
  httpGet:
    path: /
    port: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
