apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proj2.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "proj2.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "proj2.name" . }}
    spec:
      containers:
        - name: {{ include "proj2.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
